### ISSUE TITLE
This plugin shows two different users when username is changed

### ISSUE THREAD

**Issue by gurjyot** [q2apro/q2apro-most-active-users#2]
If a user changed his username then the Most Active Users plugin shows two different users. I know the activities of other users will eventually leave that unused username behind.
http://question2answer.org/qa/45131/

**Comment by q2apro** [comment]
Answered here: http://question2answer.org/qa/45131/

**Comment by gurjyot** [comment]
Nice answer, but why would someone be raising an issue if he could code the fix. 
Still thanks for the wonderful answer.
